name: CronJob

on: 
  schedule: 
    - cron: "0 7 * * *" # every day at 7am

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    environment:
      name: production-telegram-bot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Run app
        env:
          ARSENAL_GAMES_TELEGRAM_BOT_TOKEN: ${{ secrets.ARSENAL_GAMES_TELEGRAM_BOT_TOKEN }}
          ARSENAL_GAMES_TELEGRAM_BOT_CHAT_ID: ${{ secrets.ARSENAL_GAMES_TELEGRAM_BOT_CHAT_ID }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        run: npm run start
