name: CronJob

on: 
  schedule: 
    - cron: "* * * * *" # every minute

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    environment:
      name: production-telegram-bot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Run app
        run: npm run start
